name: Deploy to Production Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Recommended for Codecov

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13' # Using Python 3.13 as indicated by your venv

    - name: Install test dependencies
      run: pip install pytest pytest-cov

    - name: Run tests
      run: pytest --cov --cov-branch --cov-report=xml

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: DavidValenciaX/user-service

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 173.212.224.226 >> ~/.ssh/known_hosts

    - name: Deploy with Docker Compose
      env:
        HOST: 173.212.224.226
        USER: root
        DEPLOY_PATH: /home/projects/coffeetech_services/coffeetech_user_service/
        IMAGE_NAME: coffeetech-user-service
      run: |
        echo "Deploying to production server..."
        # Transfer files to the server
        rsync -avz --exclude '.git' --exclude '.github' --exclude '__pycache__' --exclude '.venv' ./ $USER@$HOST:$DEPLOY_PATH

        # Connect via SSH to build and restart using Docker Compose
        ssh $USER@$HOST << 'EOF'
          set -e
          cd /home/projects/coffeetech_services/coffeetech_user_service/

          echo "Stopping and removing existing containers (if any)..."
          docker compose down || true
          docker rm -f coffeetech-user-service || true

          echo "Building and starting with Docker Compose..."
          docker compose up -d --build

          echo "Cleaning up unused images..."
          docker image prune -f

          echo "Deployment completed successfully!"
        EOF